#!/bin/bash -l
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:02:00
#SBATCH -J ips_fastran
#SBATCH -e ips.err
#SBATCH -o ips.out
#SBATCH -C cpu

module load python
source activate /global/common/software/atom/perlmutter/cesol/conda/latest

export SHOT_NUMBER=000001
export TIME_ID=00001
export PATH=/pscratch/sd/h/hswils/github_repos/MANTA_DBSCANS:$PATH

ips.py --simulation=fastran_scenario.config --platform=$MACHINE_CONFIG
